# Generated by Django 5.2.9 on 2025-12-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('version', models.CharField(default='0', max_length=64)),
                ('author', models.CharField(default='unknown', max_length=255)),
                ('image', models.TextField(blank=True)),
                ('tbw', models.TextField()),
                ('reports', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
