# Generated by Django 6.0.6 on 2026-07-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_runtimeconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameServer',
        ),
        migrations.DeleteModel(
            name='RuntimeConfig',
        ),
    ]
