"""
Django settings for worldserver project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(dotenv_path: Path) -> None:
    if not dotenv_path.exists():
        return
    for raw_line in dotenv_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def _env_bool(key: str, default: bool) -> bool:
    value = os.getenv(key)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(key: str, default: int) -> int:
    value = os.getenv(key)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


def _env_list(key: str, default: list[str]) -> list[str]:
    value = os.getenv(key)
    if value is None or value.strip() == "":
        return default
    return [item.strip() for item in value.split(",") if item.strip()]


def _extract_hostname(value: str) -> str:
    text = value.strip()
    if text == "":
        return ""
    parsed = urlparse(text if "://" in text else f"http://{text}")
    return (parsed.hostname or "").strip()


def _build_allowed_hosts() -> list[str]:
    hosts = _env_list(
        "DJANGO_ALLOWED_HOSTS",
        ["127.0.0.1", "localhost", ".migetapp.com"],
    )

    for source in [
        os.getenv("PUBLIC_DJANGO_BASE_URL", ""),
        os.getenv("MIGET_APP_URL", ""),
        os.getenv("MIGET_PUBLIC_URL", ""),
        os.getenv("MIGET_HOST", ""),
    ]:
        hostname = _extract_hostname(source)
        if hostname and hostname not in hosts:
            hosts.append(hostname)

    if ".migetapp.com" not in hosts:
        hosts.append(".migetapp.com")

    return hosts


_load_dotenv(BASE_DIR / ".env")


def _resolve_sqlite_db_path() -> str:
    configured = os.getenv("DJANGO_DB_PATH", "db.sqlite3").strip()
    candidate = Path(configured)
    if not candidate.is_absolute():
        candidate = BASE_DIR / candidate

    parent = candidate.parent
    try:
        parent.mkdir(parents=True, exist_ok=True)
    except OSError:
        pass

    parent_writable = os.access(parent, os.W_OK)
    file_writable = (not candidate.exists()) or os.access(candidate, os.W_OK)
    if parent_writable and file_writable:
        return str(candidate)

    fallback = Path(
        os.getenv("DJANGO_DB_FALLBACK_PATH", "/tmp/worldserver.sqlite3").strip()
        or "/tmp/worldserver.sqlite3"
    )
    try:
        fallback.parent.mkdir(parents=True, exist_ok=True)
    except OSError:
        pass
    return str(fallback)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "change-me-in-env-for-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = _build_allowed_hosts()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal',
    'users',
    'servers',
    'config',
    'worlds',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'worldserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'worldserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _resolve_sqlite_db_path(),
    }
}


# JWT / auth settings used by API views.
JWT_SECRET = os.getenv("JWT_SECRET", "change-me-in-env-for-production")
JWT_EXPIRATION_DAYS = _env_int("JWT_EXPIRATION_DAYS", 7)

# Public runtime config defaults exposed via /api/client-config.
PUBLIC_DJANGO_BASE_URL = os.getenv("PUBLIC_DJANGO_BASE_URL", "http://127.0.0.1:8000")
PUBLIC_DJANGO_API_BASE_URL = os.getenv("PUBLIC_DJANGO_API_BASE_URL", f"{PUBLIC_DJANGO_BASE_URL}/api")
DEFAULT_NODE_API_BASE_URL = os.getenv("DEFAULT_NODE_API_BASE_URL", "")
DEFAULT_NODE_WS_URL = os.getenv("DEFAULT_NODE_WS_URL", "")
DEFAULT_WORLD_DATABASE_REPO = os.getenv(
    "DEFAULT_WORLD_DATABASE_REPO",
    "https://tinybox-worlds.caelan-douglas.workers.dev/",
)
DEFAULT_SERVER_LIST_URL = os.getenv(
    "DEFAULT_SERVER_LIST_URL",
    "https://raw.githubusercontent.com/MoyasiGinko/godot-world-release/refs/heads/main/server_list.json",
)
DEFAULT_UPDATE_RELEASE_API_URL = os.getenv(
    "DEFAULT_UPDATE_RELEASE_API_URL",
    "https://api.github.com/repos/caelan-douglas/tinybox/releases/latest",
)
DEFAULT_UPDATE_RELEASE_PAGE_URL = os.getenv(
    "DEFAULT_UPDATE_RELEASE_PAGE_URL",
    "https://github.com/caelan-douglas/tinybox/releases/latest",
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
